### ISSUE TITLE
Create blankLineAfterDeclaration linter

### ISSUE THREAD

**Issue by cvisco** [lesshint/lesshint#116]
We'd like to be able to enforce a blank new line after a declaration. For example:
```less
// bad
.thing1 {
    color: red;
}
.thing2 {
    color: blue;
}
```

```less
// good
.thing1 {
    color: red;
}

.thing2 {
    color: blue;
}
```
