### ISSUE TITLE
Add selector length option to singleLinePerSelector?

### ISSUE THREAD

**Issue by cvisco** [lesshint/lesshint#117]
For very short selectors, it would be nice to let them live on one line. 

The [18F Style Guide](https://pages.18f.gov/frontend/css-coding-styleguide/format/) specifies this as "Multiple selectors should each be on a single line, with no space after each comma, unless [the] selector is less than five chars." 

I tend to follow this as well, just out of habit:

```less
// bad
.selector1, .selector2 {
    color: red;
}

// good
.selector1,
.selector2 {
    color: red;
}

// also good (if allowed via option)
h1, h2, h3, h4, h5 {
    color: blue;
}
```
