### ISSUE TITLE
qualifyingElement linter should allow `&.classname` form

### ISSUE THREAD

**Issue by cvisco** [lesshint/lesshint#118]
The following is valid in my opinion, but qualifyElement flags the `&.is-active`:
```less
.widget {
    color: black;

    &.is-active {
        color: red;
    }
}
```

This would apply to things like `&[disabled]` as well
