### ISSUE TITLE
spaceAroundComma linter breaks on multiline definition

### ISSUE THREAD

**Issue by cvisco** [lesshint/lesshint#119]
For very long definitions, as you might find with gradients, we'd like to be able separate each step on to a new line without the `spaceAroundComma` linter flagging it. Perhaps this needs to be an additional option?

Something like the following should be considered valid, in my opinion:
```less
.thing {
    background: linear-gradient(
        to bottom,
        transparent 0,
        transparent 25%,
        red 25%,
        red 75%,
        transparent 75%,
        transparent 0
    );
}
```

**Comment by kokarn** [comment]
LGTM. 
The problem is with how to filter where it's available or not. 
Maybe a list of excluded properties?

**Comment by jwilsson** [comment]
I think an `exclude` option sounds overkill, but definitely something like `newline-after` and `newline-before` values for the `style` option.

**Comment by kokarn** [comment]
But won't that lead to some things not being linted correctly? 
Because it's just the linear-gradient that you want to allow newlines for not say font.
Or is that expected behaviour then?
```css
.thing {
    font: 
        14px,
        Roboto,
        #000;
}
```
