### ISSUE TITLE
Feature request: mixins should be at top of blocks

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#125]
Invalid:

```less
.a {
  color: red;
  .something();
}
```

Valid:

```less
.a {
  .something();
  color: red;
}
```

(Ideally I want a newline after them too but I won't ask for too much :smile: )
