### ISSUE TITLE
Feature request: empty line between blocks

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#126]
Invalid:

```less
.a {
  color: red;
}
.b {
  color: blue;
}
```

Valid:

```less
.a {
  color: red;
}

.b {
  color: blue;
}
```
