### ISSUE TITLE
Feature request: selector with descendants should be nested

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#127]
Valid:

```less
.a .b {
  color: red;
}
```

Valid:

```less
.a {
  .b {
    color: red;
  }
}
```

Some people want to avoid nesting because of style preference or laziness but this is actually good for maintainability. If I need to add a rule to `.a`, I don't have to convert it from the invalid example to the valid example before adding my rule.

**Comment by adam-lynch** [comment]
Although... Maybe only when it's the only selector; this is only valid in my opinion since it's sharing code:

```less
.a,
.b .c {
  color: red;
}
```

I wonder what others think.
