### ISSUE TITLE
qualifyingElement should allow `&`

### ISSUE THREAD

**Issue by adam-lynch** [lesshint/lesshint#131]
This fails:

```less
.button-base(
  @baseBackgroundColour,
  @focusBackgroundColor: @baseBackgroundColour,
  @hoverBackgroundColour: lighten(@baseBackgroundColour, @buttonBackgroundDelta),
  @activeBackgroundColour: darken(@baseBackgroundColour, @buttonBackgroundDelta)
) {
  // ...
  &[disabled] {
    background: gray;
  }
  // ...
}
```
