### ISSUE TITLE
False Positive with "decimalZero"

### ISSUE THREAD

**Issue by CITguy** [lesshint/lesshint#137]
Given `decimalZero: "leading"` and the following Less code...

```less
.foobar {
  color: rgba(255, 255, 255, .5);
}
```

I should get an error on line 2, because `.5` should be `0.5`
