### ISSUE TITLE
Important mixins

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#159]
Input:

```less
.foo() {
    bar: blah;
}

.test {
    .foo() !important;
}
```

Output:

    Error: test.less: line 6, col 1, parse error: Please check validity of the block starting from line #6 

LESS itself handles it correctly.
