### ISSUE TITLE
Less hint breaks with variables inside selector

### ISSUE THREAD

**Issue by ondrejsevcik** [lesshint/lesshint#170]
Hi, I think I run into similar issue as in #64. When I lint my *.less files it throws an error `Please check validity of the block starting from line #2`

```css
  .label--color(@colorname, @color, @background-color) {
  	&--@{colorname} { // <---- this is the line
  		color: @color;
  		background-color: @background-color;
  	}
  }
```
