### ISSUE TITLE
Rule request: ban unsupported browser prefixes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#195]
Problem: After raising the minimum supported version of a browser it can be painful to find vendor-prefixed tags that are no longer required for that browser. This means wasteful CSS. It adds up, especially when defining common mixins for commonly-prefixed attributes such as `flex`.

Solution: It would be great to have a rule that takes in a set of minimum browser versions and complains when an unnecessary tag is added.

```js
"minimum-browser-support": {
    "Firefox": 56
}
```

```less
.foo {
    -moz-hyphens: none; // violation: not necessary in Firefox >43
    hyphens: none;
}
```
