### ISSUE TITLE
decimalZero 2.0 bugs

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#196]
actual `master` branch

```css
.test-rule {
    font-family: ForalPro, sans-serif;
    font-style: normal;
    font-weight: 300;
}
```
> Warning: foral-pro.less: line 1, col 18, decimalZero: 300 should be written without leading and trailing zero.

second problem: `line 1`, should be `4`

Same with:
```css
@font-size-base: 1rem;
```
```css
.tags-view {
    font-size: (15 * @base);
}
```
