### ISSUE TITLE
Inline rules not working as expected

### ISSUE THREAD

**Issue by garethwhittaker** [lesshint/lesshint#221]
This works:

``` less
// lesshint duplicateProperty: false
.nav {
    background: data-uri('/url/here.png'), -webkit-linear-gradient(#379793, #27726d);
    background: data-uri('/url/here.png'), -moz-linear-gradient(#379793, #27726d);
    background: data-uri('/url/here.png'), -ms-linear-gradient(#379793, #27726d);
    background: data-uri('/url/here.png'), -o-linear-gradient(#379793, #27726d);
    background: data-uri('/url/here.png'), linear-gradient(#379793, #27726d);
}
```

This doesn't:

``` less
body {
    // lesshint duplicateProperty: false
    .nav {
        background: data-uri('/url/here.png'), -webkit-linear-gradient(#379793, #27726d);
        background: data-uri('/url/here.png'), -moz-linear-gradient(#379793, #27726d);
        background: data-uri('/url/here.png'), -ms-linear-gradient(#379793, #27726d);
        background: data-uri('/url/here.png'), -o-linear-gradient(#379793, #27726d);
        background: data-uri('/url/here.png'), linear-gradient(#379793, #27726d);
    }
}
```

Would be great if we could apply rules to a specific section rather than only at the start of a file or by applying multiple single-line rules.

**Comment by jwilsson** [comment]
I like the idea, not sure how easy/hard it'll be to implement though. But let's hear some other people's thoughts too.

**Comment by shellscape** [comment]
@jwilsson spitballing here - do we have a means of linking comments to rules / properties? I know there's `walkComments` and `walk` that are separate, but I don't know off hand if comments show up in the `walk` method, or if they're accessible from the individual `Node`s.

**Comment by shellscape** [comment]
Autoprefixer appears to do what we're after https://github.com/postcss/autoprefixer. Going to investigate further.

**Comment by shellscape** [comment]
Right, so when using `ast.root.walk(function (node) {` we get a flat set of nodes to traverse through (that we don't have to recurse through) and that list just so happens to include comments as well. so we *can* inspect the previous node for a config-comment and then apply that rule(set) to the current node. The trick is applying some kind of block-scope.

Now, we're already using a `lineOptions` collection to check each node/line against for linter config. We could modify that with a `start` and `end` to denote a block-scope, and as long as the current node falls within the start-to-end block scope, we apply the rule. 

Of course, we'll have to require that the `/* */` comment format be used for block scope, because otherwise I dunno how we'd differentiate between line-config and block-config. Curiously enough, ESLint doesn't appear to have block-scope vs. file-scope documented anywhere. Only file-scope and line-scope.

So there's the leg work into what it would take - do we want to make this happen?

**Comment by jwilsson** [comment]
I've been thinking of another approach (after looking at how Autoprefixer does it). Bear with me, I'll try to explain.

1. We check the first child node of the current traversed node's parent. See an example below.
2. If it's a comment, try to parse it for inline options.
3. If it contains inline options, merge/replace the options for the linter(s) specified in the comment.
4. If the comment doesn't contain options, repeat the above steps for the parent's parent and so forth, until we find a match or reach the root. 

In theory, we could use this for the current file-wide options since we'll eventually get to the root and check the first comment there.


Example for point 1.
```less
.foo {
    // We walk up the tree until we find something, for example this comment
    /* lesshint emptyRule: false */
    color: red;

    .bar {
        .baz {
            // Won't report this since it's disabled in a parent
        }
    }
}
```

I have no idea whether this will work but it's perhaps another possible solution.
