### ISSUE TITLE
spaceAroundOperator doesn't like prefixed functions

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#222]
```css
test {
    background-image: -webkit-linear-gradient(xxx);
}
```

```
Warning: test.less: line 2, col 19, spaceAroundOperator: Operators should be preceded and followed by one space.
```
