### ISSUE TITLE
spaceBeforeBrace reports wrong column/line on multi-line selectors

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#231]
Given this code:

``` less
.foo,
.bar  { // Note the two spaces
    color: red;
}
```

And this config:

``` json
{
    "spaceBeforeBrace": {
        "enabled": true,
        "style": "one_space"
    }
}
```

it gives the following report:

```
Warning: test.less: line 1, col 11, spaceBeforeBrace: Opening curly brace should be preceded by one space.
```

Which is clearly wrong.
