### ISSUE TITLE
newlineAfterBlock with nested blocks

### ISSUE THREAD

**Issue by solidevolution** [lesshint/lesshint#245]
Hello,

if got problems to resolve the following warning(s)

```
Warning: app.less: line 1636, col 5, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1641, col 3, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1644, col 5, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1649, col 3, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1652, col 5, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1657, col 3, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1660, col 5, newlineAfterBlock: All blocks should be followed by a new line.
```
It works not on nested blocks for me. Here is my less source: (starting from line 1631)

```
/* Animations */
[ui-view] {
  &.ng-enter {
    opacity: 0;
    transition: 0.25s linear all;
    &.ng-enter-active {
      opacity: 1;
    }
  }

  &.ng-add {
    opacity: 0;
    transition: 0.25s linear all;
    &.ng-add-active {
      opacity: 1;
    }
  }

  &.ng-leave {
    opacity: 1;
    transition: 0.25s linear all;
    &.ng-leave-active {
      opacity: 0;
    }
  }

  &.ng-remove {
    opacity: 1;
    transition: 0.25s linear all;
    &.ng-remove-active {
      opacity: 0;
    }
  }
}
```

I found nothing about nested formatting in your documentation, so I tried some cases but always got

`newlineAfterBlock: All blocks should be followed by a new line.`

or

`trailingWhitespace: There should't be any trailing whitespace.`

How should the less code structured to remove the warning? Or is it a bug?

**Comment by jwilsson** [comment]
Hi,
I think the code you posted should be reported. Writing it like this should pass:
```less
/* Animations */
[ui-view] {
  &.ng-enter {
    opacity: 0;
    transition: 0.25s linear all;

    /* Animations */
    &.ng-enter-active {
      opacity: 1;
    }
  }

  &.ng-add {
    opacity: 0;
    transition: 0.25s linear all;

    &.ng-add-active {
      opacity: 1;
    }
  }

  &.ng-leave {
    opacity: 1;
    transition: 0.25s linear all;

    &.ng-leave-active {
      opacity: 0;
    }
  }

  &.ng-remove {
    opacity: 1;
    transition: 0.25s linear all;

    &.ng-remove-active {
      opacity: 0;
    }
  }
}
```

I did however, find a bug which prevents that from passing correctly.

**Comment by solidevolution** [comment]
Tried it with 2.1.1, same there ...

**Comment by jwilsson** [comment]
Strange, the example I posted is correct IMO and isn't reported by the linter in `2.1.1`.

I'll reopen so we can investigate further.

**Comment by tkazec** [comment]
This does not work:

```less
a {
    foo: bar;
    
    b {
        foo: bar;
    }
}
```

This does:

```less
a {
    b {
        foo: bar;
    }
}
```

@jwilsson in your test, `source` actually evaluates to this, which passes but is itself wrong:

```less
.foo {    color: red;

    .bar {        color: red;    }}
```
