### ISSUE TITLE
Valid LESS but Invalid parsed results

### ISSUE THREAD

**Issue by MichelGratton** [lesshint/lesshint#256]
This LESS mixin code is valide and works perfectly

``` less
.output((unit(extract(@pxValues, @idx)) / unit(@application-base-font-size)));
```

But, lesshint will fail and trhow an error: Error: Expected opening parenthesis.

If I move the extract part to a variable and I use this variable, everything is find:

``` less
@curVal: extract(@pxValues, @idx);
.output((unit(@curVal) / unit(@application-base-font-size)));
```

**Comment by shellscape** [comment]
Can you provide a stack trace please?

**Comment by MichelGratton** [comment]
I don't have the stack trace, but you can try it using my pixel to rem mixins. First set a value for the `@application-base-font-size` variable:
```less
@application-base-font-size: 14px;
```
Here is the mixin:
```less
.px2rem(@property, @pxValues...) {
    @length: length(@pxValues);

    // Loop through all pixels values
    .loop(@idx) when (@idx <= @length) and (@length > 0) {
        // Scope Output mixin to output without 'rem' unit if value is 0
        .output(@value) when (@value = 0) {
            @{property}+_: @value;
        }
        // Scope Output mixin to output with 'rem' unit
        .output(@value) when (default()) {
            @{property}+_: unit(@value, rem);
        }
        // Extract current argument index value
        .output((unit(extract(@pxValues, @idx)) / unit(@application-base-font-size)));

        .loop((@idx + 1));
    }

    .loop(1);
}
```
and just use the mixin with some properties:
```less
.px2rem(margin, 7px 14px); // output -> margin: 0.5rem 1rem;
.px2rem(font-size, 21px); // output -> font-size: 1.5rem;
```
Execute your lesshint task and it will fail with an error: Expected opening parenthesis.

---
Now change the last .output line to use the extract part in a variable and use this new variable instead, and everything works just fine:
```less
// Extract current argument index value
@curVal: extract(@pxValues, @idx);
.output((unit(@curVal) / unit(@application-base-font-size)));
```
Hope this help enough.
