### ISSUE TITLE
Rule proposal: universalSelector

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#266]
Should work just like `idSelector`, disallow the use of universal selectors (i.e. `*`).

Should report:

``` less
* {
  color: red;
}

.foo * {
  color: red;
}
```

Shouldn't report:

``` less
a {
  color: red;
}

.foo a {
  color: red;
}
```

**Comment by shellscape** [comment]
I like it.

**Comment by kokarn** [comment]
Needs more cowbell/options? Do we always want to disallow this? Or just global scope?

**Comment by deanc** [comment]
Hi @jwilsson - going to bring this one back from the dead too. It'd be nice to make this slightly more configurable also.

I would argue that such a rule in some cases might be nice. In fact it's usually the rule I write first in any CSS file to reset all browser styles to the same.

```less
* {
  box-sizing: border-box;
  margin:0;
  padding: 0;
}
```

Perhaps adding an option to allow the universal selector in the global scope, but disallow it in the form: `.foo *`.
