### ISSUE TITLE
Odd column numbers in space_around_operator

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lesshint/lesshint#343]
**Which version of `lesshint` are you using?**

3.0.1.

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

Node.js API via `autolesshint`.

**What's your `.lesshintrc` configuration?**

```js
{
    // ... (all other rules are disabled)
    "spaceAroundOperator": {
        "enabled": true,
        "style": "both"
    }
    // ...
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.aaa {
    height: calc(12px+34px);
                       ^
}

.bbb {
    height: calc(12px +34px);
                         ^
}

.ccc {
    height: calc(12px+ 34px);
                       ^
}

.ddd {
    height: calc(12px + 34px);
}
```

**What did you expect to happen?**

One of the following:
* One error per line, each at column 22 or 23 for the start of the operator's spacing or the operator itself
* One error per lack of spacing, each at the place the space should be

**What's the actual result?**

Three errors, at columns 24, 26, and 24. See `^`s above.
