### ISSUE TITLE
Operators shouldnt be preceded and  followed by one space if this operator is not an operator but just a char.

### ISSUE THREAD

**Issue by aloisdg** [lesshint/lesshint#349]
**Which version of `lesshint` are you using?**

last one

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

gulp-lesslint

**What's your `.lesshintrc` configuration?**

vanilla

**If you're reporting a bug, please show us some code that's failing.**

```less
        margin-right: -(@grid-gutter-width / 4);
```

**What did you expect to happen?**

    {nothing}

**What's the actual result?**

    Warning: tables.less: line 13, col 25, spaceAroundOperator: Operators should be preceded and followed by one space.

**Would you be interested in submitting a PR for this issue?**

Why not

----

alternativ:

`@grid-whatever-width` shouldn't be allowed as name at all...

**Comment by kokarn** [comment]
I would assume it's actually warning on the ```-(``` part. 
Can you test with ```- (``` instead?

**Comment by aloisdg** [comment]
well

```less
margin-left: @grid-gutter-width;
margin-left: @grid-gutter-width / 4;
margin-left: (@grid-gutter-width / 4);
margin-left: (@grid-gutter-width / 4);
margin-left: - (@grid-gutter-width / 4); //false
margin-left: - @grid-gutter-width;
margin-left: - (@grid-gutter-width); // false
```

**Comment by kokarn** [comment]
So you get errors on all lines but 
```
margin-left: - (@grid-gutter-width / 4);
margin-left: - (@grid-gutter-width);
```
Am I understanding you correctly?

**Comment by aloisdg** [comment]
```less
        margin-left: - (@grid-gutter-width / 4); // ko
        margin-left: - @grid-gutter-width;
        margin-left: - (@grid-gutter-width); // ko
        margin-left: -(@grid-gutter-width / 4); // ko
        margin-left: -@grid-gutter-width;
        margin-left: -(@grid-gutter-width); // ko
        margin-left: -1px;
        margin-left: -(1px);
```

**Comment by kokarn** [comment]
Can confirm somethings fucky.

lesshint 3.0.1
```less
@grid-gutter-width: 14px;

a {
    margin-left: - (@grid-gutter-width / 4); // fails
}

b {
    margin-left: - @grid-gutter-width; // fails
}

c {
    margin-left: - (@grid-gutter-width); // fails
}

d {
    margin-left: -(@grid-gutter-width / 4); // fails
}

e {
    margin-left: -@grid-gutter-width; // ok
}

f {
    margin-left: -(@grid-gutter-width); // fails
}

g {
    margin-left: -1px; // ok
}

h {
    margin-left: -(1px); // fails
}
```

```bash
Warning: test.less: line 4, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.
Warning: test.less: line 8, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.
Warning: test.less: line 12, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.
Warning: test.less: line 16, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.
Warning: test.less: line 24, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.
Warning: test.less: line 32, col 20, spaceAroundOperator: Operators should be preceded and followed by one space.
```
