### ISSUE TITLE
Inline Configuration with Multiple Selectors

### ISSUE THREAD

**Issue by ericsakmar** [lesshint/lesshint#371]
**Which version of `lesshint` are you using?**
3.1.1

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
cli

**What's your `.lesshintrc` configuration?**
default

**If you're reporting a bug, please show us some code that's failing.**

```less
#foo, // lesshint idSelector:false
#bar { // lesshint idSelector:false
   background-color: black;
}
```

**What did you expect to happen?**
no warnings

**What's the actual result?**
```
Warning: test.less: line 1, col 1, idSelector: Selectors should not use IDs.
```

**Would you be interested in submitting a PR for this issue?**
Sure!
