### ISSUE TITLE
Enhanced inline configuration option comments

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#404]
I've been thinking of replacing the [current inline configuration options](https://github.com/lesshint/lesshint/blob/7d717edbc060cc2c9ba2523aed6eb5db1f7c5b6b/docs/user-guide/configuration.md#inline-configuration) with some more fine grained ones. The new ones will not support anything else but disabling/enabling of rules already configured in `.lesshintrc`.

But the upsides will be:
* Disable/enable rules anywhere in a file.
* Define a range where a rule should be disabled.
* Easily disable rules on the current line or the line after.
* Easier maintenance for us.
* It'll work more as users expect it to.

What I think it should look like:
```less
// lesshint-disable spaceBeforeBrace
.foo{ // This line won't be reported since we disabled the rule
    color: red;
}
// lesshint-enable spaceBeforeBrace

.bar{ // But this line will be reported since we enabled the rule again
    color: blue;
}

.foo {
    color: red !important; // lesshint-disable-line importantRule
}

.foo {
    // lesshint-disable-next-line maxCharPerLine
    background-image: url('A really long url...');
}
```

I've started poking at a implementation but I'd like some feedback before finishing it.
