### ISSUE TITLE
Browser prefixed properties report failures for `spaceAroundOperator`

### ISSUE THREAD

**Issue by donotknow** [lesshint/lesshint#433]
### Example failing unit test

Here is an example of a failing test (didn’t seem worth it for me to create a fork/PR because I didn’t figure out where/how I should assert and fix on the underlying `postcss-values-parser` side of the house):

```js
            it('should not report on browser-prefixed properties', function () {
                const source = 'transition-property: opacity -webkit-filter;';

                return spec.parse(source, function (ast) {
                    const result = spec.linter.lint(options, ast.root.first);

                    expect(result).to.be.undefined;
                });
            });
```

### More practical failing test

`.lesshintrc`
```json
{
    "spaceAroundOperator": {
        "enabled": true,
        "severity": "error",
        "style": "both"
    }
}
```

`style.less`
```less
.my-thing {
	opacity: 0.5;
	-webkit-filter: blur(8px);
	filter: blur(8px);
	transition: opacity -webkit-filter 0.5s ease-out;
	transition-property: opacity filter;
}
.my-thing.transition {
	opacity: 0.5;
	-webkit-filter: blur(0);
	filter: blur(0);
}
```

```
Error: style.less: line 5, col 22, spaceAroundOperator: Operators should be preceded and followed by one space.
```
----

```
├─┬ lesshint@4.1.2
│ └── postcss-values-parser@1.2.2 
```
