### ISSUE TITLE
Disabling a rule with an inline comment is not working

### ISSUE THREAD

**Issue by kaiyoma** [lesshint/lesshint#442]
**Which version of `lesshint` are you using?**
4.4.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI (via yarn)

**What's your `.lesshintrc` configuration?**

```js
{
  "excludedFiles": [
    "src/stylesheets/fonts/*.less"
  ],
  "idSelector": {
    "enabled": false
  },
  "qualifyingElement": {
    "allowWithClass": true
  },
  "spaceAroundComma": {
    "allowNewline": true
  },
  "universalSelector": {
    "enabled": false
  },
  "zeroUnit": {
    "style": "no_unit"
  }
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.foo {
  height:100%; // lesshint-line spaceAfterPropertyColon: false

  .bar {
    overflow-x: hidden !important; // lesshint-line importantRule: false
  }
}
```

**What did you expect to happen?**
No errors.

**What's the actual result?**
Two errors.

**Comment by jwilsson** [comment]
Hi!
We always use prefix inline config comments with just `lesshint`. Even if they're just targeting a single line. 

So this should do what you expect:
```less
.foo {
  height:100%; // lesshint spaceAfterPropertyColon: false

  .bar {
    overflow-x: hidden !important; // lesshint importantRule: false
  }
}
```

There are plans on enhancing the inline config comments, check out #404 if you're interested in helping out!
