### ISSUE TITLE
[propertyOrdering] not working inside @media without selector

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#460]
**Which version of `lesshint` are you using?**
v4.6.4

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI

**If you're reporting a bug, please show us some code that's failing.**

```less
.test1 {
    margin: 0;

    @media (min-width: 320px) {
        .test2 {
            color: red;
            border: 0 none;
        }
    }

    @media (min-width: 768px) {
        color: red;
        border: 0 none;
    }
}
```

**What did you expect to happen?**
> Warning: styles.less: line 8, col 13, propertyOrdering: Property ordering is not alphabetized
> Warning: styles.less: line 14, col 9, propertyOrdering: Property ordering is not alphabetized

**What's the actual result?**
> Warning: styles.less: line 8, col 13, propertyOrdering: Property ordering is not alphabetized
