### ISSUE TITLE
Upgrade report on propertyOrder error

### ISSUE THREAD

**Issue by Tiross** [lesshint/lesshint#498]
**Which version of `lesshint` are you using?**
5.2.1

**Example** (with alphabetized order)

```less
.foo {
  bottom: 0;
  position: absolute;
  right: 0;
  top: 0;
  left: 0;
}
```

**What did you expect to happen?**

Report the `left` property and indicate that it should be before `position`.

**What's the actual result?**

`"left" should be before "top"`
