### ISSUE TITLE
Add validateIndentation

### ISSUE THREAD

**Issue by CITguy** [lesshint/lesshint#50]
My team uses 4 spaces per indentation. It would be nice to have a linter to check that indentation is correct. Something along the lines of the following (with suggested defaults):

#### syntax
```
"validateIndentation": {
  "enabled": true,
  "style": "spaces",
  "quantity": 4
}
```

#### options
**style** (string)

* spaces (default)
* tabs

**quantity** (integer) number of spaces/tabs per indentation

* 2 (default)
* user defined value

**Comment by jwilsson** [comment]
I think this will be quite easy once [e8bdc3be2e34ff369f3b0f8ee699a1262a97b8a0 in `gonzales-pe`](https://github.com/tonyganch/gonzales-pe/commit/e8bdc3be2e34ff369f3b0f8ee699a1262a97b8a0) gets published on npm. 

We should be able to multiply the `level` argument with each `column` property in the AST. And then check that value against the `quantity` value multiplied with `level`.

**Comment by kokarn** [comment]
I recently got a file that looks something like this
```
.class {
    property: value;

    next-property: value;

    .otherClass {
          property: value;
    }

    third-property: value;
}
```

Maybe newlines and all properties on top should be in this linter as well? Or separate?

**Comment by CITguy** [comment]
Well, this is an interesting case.  What should the CSS look like?

## What should the LESS look like?

### Apply Linting to Properties

#### Option 1.0 - No blank lines before or after property definitions
```less
.class {
  property: value;
  next-property: value;
  .otherClass {
    property: value;
  }
  third-property: value;
}
```

#### Option 1.1 - Blank line before property definition
```less
.class {

  property: value;

  next-property: value;
  .otherClass {

    property: value;
  }

  third-property: value;
}
```

#### Option 1.2 - Blank line after property definition
```less
.class {
  property: value;

  next-property: value;

  .otherClass {
    property: value;

  }
  third-property: value;

}
```

#### Option 1.2 - Blank lines around property definition
```less
.class {

  property: value;

  next-property: value;

  .otherClass {

    property: value;

  }

  third-property: value;

}
```

### Apply Linting to Style Block

### Option 2.0 - Blank line before block
```less
.class {
  property: value;
  next-property: value;

  .otherClass {
    property: value;
  }
  third-property: value;
}
```

### Option 2.1 - Blank line after block
```less
.class {
  property: value;
  next-property: value;
  .otherClass {
    property: value;
  }

  third-property: value;
}
```

### Option 2.2 - Blank lines around block
```less
.class {
  property: value;
  next-property: value;

  .otherClass {
    property: value;
  }

  third-property: value;
}
```

## Challenge
The challenge to the desired state of the LESS is that it will be difficult to apply a single linter to address all of the above options.  However, if you apply multiple linters (property and block), you are likely to get conflicts between the linters (even for the same linter).

## Suggestion
Because new line linting is difficult to apply to both properties and blocks, and because a minifier/compiler doesn't care about new lines, I see the least common denominator to be the following.

0. I would suggest adding a `blankLinesAroundBlock` (**none** | before | after | both), and optionally a `blankLinesWithinBlock` (**none** | open | close | both) linter to apply new line linting at the block-level only.
0. For property level linting, I would add a `maxConsecutiveBlankLines` linter (default: 1) that would check for situations where you have an inconsistent number of blank lines between block/property definitions.  This linter would allow for a tolerance rather than an exact value (0 to N blank lines between definitions).
