### ISSUE TITLE
Ordering bug 

### ISSUE THREAD

**Issue by Tiross** [lesshint/lesshint#500]
**Which version of `lesshint` are you using?**
5.2.0

**If you're reporting a bug, please show us some code that's failing.**

```less
.btn {
  border: 0; // Known in concentric properties
  appearance: none; // Unknown in concentric
}
```

**What did you expect to happen?**

No report

**What's the actual result?**
```
Warning: method-list.less: line 5, col 5, propertyOrdering: "appearance" expected to be before "border"
```

**Explaination** 
The first unknown property is tested against the last known (in alphabetical order).
