### ISSUE TITLE
"parse error: Missed semicolon" for variable body starting with `&`

### ISSUE THREAD

**Issue by fabb** [lesshint/lesshint#502]
**Which version of `lesshint` are you using?**

5.3.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**

Webpack LessHintPlugin

**What's your `.lesshintrc` configuration?**

```js
{
    "emptyRule": false,
    "spaceAfterPropertyName": false,
    "propertyOrdering": false,
    "zeroUnit": ["no_unit"],
    "importPath": [true, false],
    "singleLinePerSelector": false,
    "qualifyingElement": false,
    "universalSelector": false,
    "duplicateProperty": ["display"],
    "maxCharPerLine": 150,
    "importantRule": false
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
@just-text-type-input-selectors: &:not([type='file']):not([type='checkbox']):not([type='radio']):not([type='range']):not([type='hidden']);

input {
	@{just-text-type-input-selectors} {
		color: blue;
	}
}
```

**What did you expect to happen?**

This should parse and show no linter errors

**What's the actual result?**

`parse error: Missed semicolon`

**Would you be interested in submitting a PR for this issue?**

Sorry, no

**Related**

This might be related to https://github.com/shellscape/postcss-less/issues/123
