### ISSUE TITLE
Lesshint Throws Different Warnings for Single Line Comments

### ISSUE THREAD

**Issue by fabb** [lesshint/lesshint#504]
**Which version of `lesshint` are you using?**
6.0.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
Via npm run script or just `npx lesshint path/to/style.less`

**What's your `.lesshintrc` configuration?**

```js
{
    "excludedFiles": ["node_modules"],
    "emptyRule": false,
    "spaceAfterPropertyName": false,
    "propertyOrdering": false,
    "zeroUnit": ["no_unit"],
    "importPath": [true, false],
    "singleLinePerSelector": false,
    "qualifyingElement": false,
    "universalSelector": false,
    "duplicateProperty": ["display"],
    "maxCharPerLine": 180,
    "importantRule": false,
    "spaceAroundComma": {"allowNewline": true},
    "spaceAfterPropertyColon": {"style": "at_least_one_space"}
}
```

**Code that's failing:**

Example 1:
```less
// reset cms-article paddings in case <CMS> is used

.cms-article {
    padding: 0;
}
```

Example 2:
```less
// h* + section (recursively)
section {
    padding: 0;
}
```

Example 3:
```less
///////////////////////////////////////////////////////////////////////////////
// Article Grid Layout (2fr+1fr)
///////////////////////////////////////////////////////////////////////////////
.wh-article-grid {
    display: grid;
}
```

**What did you expect to happen?**

No lesshint warnings.

**What's the actual result?**

Example 1+2: `singleLinePerProperty` warning on the line of `.cms-article`/`.section`.
Example 3: `newlineAfterBlock:` warning on the line of `.wh-article-grid`.

**Would you be interested in submitting a PR for this issue?**

Phew, sorry, no.
