### ISSUE TITLE
False positive with "singleLinePerProperty"

### ISSUE THREAD

**Issue by CITguy** [lesshint/lesshint#51]
`singleLineProperty` is returning a false positive for inline comments.

Valid CSS

```LESS
.foo {
  background-color: #000;
  color: #000; // black on black
}
```

Shouldn't error
```
test.less: line 3, col 5, singleLinePerProperty: Each property should be on it's own line.
```

Please add support for inline comments
