### ISSUE TITLE
newlineAfterBlock doesn't work properly

### ISSUE THREAD

**Issue by xavierfoucrier** [lesshint/lesshint#510]
**Which version of `lesshint` are you using?**
6.3.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
[linter-lesshint](https://atom.io/packages/linter-lesshint)

**What's your `.lesshintrc` configuration?**
```json
"newlineAfterBlock": {
  "enabled": true
}
```

**If you're reporting a bug, please show us some code that's failing.**

```less
.banner {
  position: relative;
  @media (min-width: @tablet) { // an error is properly displayed for this line
    max-width: 50vw;
    max-height: 50vh;
  } // error should be displayed here
  .mask(url('@{svg-symbol}') 50% no-repeat);
}
```

**What did you expect to happen?**
Error: lesshint: newlineAfterBlock: All blocks should be followed by a new line

**What's the actual result?**
pass
