### ISSUE TITLE
spaceBeforeBrace doesn't check media queries

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#61]
The following code, which should be marked as a violation passes:

```
@media(all){

}
```

This should be as simple as adding another node type to check for.

@kokarn you wanna take it?

**Comment by kokarn** [comment]
Yeah, if it's no rush? Might not be able to look at it until next week

**Comment by kokarn** [comment]
Actually, this seems to be a bit trickier.
If the code is nested, it is checked but the column is wrong
```less
.class {
    color: red;

    @media screen and ( max-width: 480px ){
        color: blue;
    }
}
```
test.less: line 4, col 25, spaceBeforeBrace: Opening curly brace should be preceded by one space

Where this just passes
```
@media screen and ( max-width: 480px ){
    color: blue;
}
```
