### ISSUE TITLE
propertyOrdering:alpha is examining free-standing groups of variables

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#95]
One of our devs ran across this yesterday and we spent some time verifying it. Haven't looked into why yet, but I'm suspecting that gonzales-pe is grouping blocks of vars together. The following block is throwing linting errors for `propertyOrdering: alpha`, on `@borderColor: #dfdfdf;`

``` css
/*

 ____     __                     __                       __
/\  _`\  /\ \                   /\ \                     /\ \__
\ \ \/\_\\ \ \___      __    ___\ \ \/'\     ___   __  __\ \ ,_\
 \ \ \/_/_\ \  _ `\  /'__`\ /'___\ \ , <    / __`\/\ \/\ \\ \ \/
  \ \ \L\ \\ \ \ \ \/\  __//\ \__/\ \ \\`\ /\ \L\ \ \ \_\ \\ \ \_
   \ \____/ \ \_\ \_\ \____\ \____\\ \_\ \_\ \____/\ \____/ \ \__\
    \/___/   \/_/\/_/\/____/\/____/ \/_/\/_/\/___/  \/___/   \/__/

  This file will import the necessary files for checkout and provide
  general styles and mixins for use across the checkout pages

*/
@import '../reset';
@import '../forms';
@import 'new_nouveau';
@import 'step_select';
@import 'review';
@import 'overview';
@import 'select';
@import 'payment';
//@import '../address_choice_modal';

@layoutSuperWideWidth: 960px; //1280px when we need to bring it back
@layoutWideWidth: 960px;
@layoutMediumWidth: 756px;
@layoutNarrowTinyWidth: 100%;
@borderColor: #dfdfdf;
@darkGrey: #737373;
@basePadding: 15px;
@baseFontSize: 15px;
*,
*:before,
*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
body {
  font-size: @baseFontSize;
}
```
