### ISSUE TITLE
propertyOrdering: alpha, asterisks hack

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#96]
We've got this wonky bit in code:

``` css
.inline-block () {
  display: inline-block;
  *display: inline; /* IE7 inline-block hack */
  *zoom: 1;
}
```

The linter thinks that `*display` is less than `display` without an asterisk. Not sure how that should be handled. The order is necessary for the css hack to work. Maybe a property like `ignorePrefixes: ['*']` ? Thoughts?
